// =====================================================
// PeopleHub — Mock HR Data
// =====================================================

const DEPARTMENTS = [
  "Engineering",
  "Product",
  "Design",
  "Marketing",
  "Human Resources",
  "Finance",
  "Sales",
  "Operations",
];

const employees = [
  {
    id: "EMP-001",
    name: "Arjun Mehta",
    email: "arjun.mehta@peoplehub.io",
    role: "Senior Frontend Engineer",
    department: "Engineering",
    status: "active",
    joinDate: "2023-03-15",
    avatar: null,
    phone: "+91-98765-43210",
    location: "Bangalore, India",
  },
  {
    id: "EMP-002",
    name: "Priya Sharma",
    email: "priya.sharma@peoplehub.io",
    role: "Product Manager",
    department: "Product",
    status: "active",
    joinDate: "2022-07-01",
    avatar: null,
    phone: "+91-87654-32109",
    location: "Mumbai, India",
  },
  {
    id: "EMP-003",
    name: "Ravi Kumar",
    email: "ravi.kumar@peoplehub.io",
    role: "UX Designer",
    department: "Design",
    status: "on-leave",
    joinDate: "2023-01-10",
    avatar: null,
    phone: "+91-76543-21098",
    location: "Hyderabad, India",
  },
  {
    id: "EMP-004",
    name: "Sneha Patel",
    email: "sneha.patel@peoplehub.io",
    role: "Marketing Lead",
    department: "Marketing",
    status: "active",
    joinDate: "2021-11-20",
    avatar: null,
    phone: "+91-65432-10987",
    location: "Pune, India",
  },
  {
    id: "EMP-005",
    name: "Vikram Singh",
    email: "vikram.singh@peoplehub.io",
    role: "HR Business Partner",
    department: "Human Resources",
    status: "on-leave",
    joinDate: "2022-04-05",
    avatar: null,
    phone: "+91-54321-09876",
    location: "Delhi, India",
  },
  {
    id: "EMP-006",
    name: "Ananya Reddy",
    email: "ananya.reddy@peoplehub.io",
    role: "Financial Analyst",
    department: "Finance",
    status: "active",
    joinDate: "2023-06-18",
    avatar: null,
    phone: "+91-43210-98765",
    location: "Chennai, India",
  },
  {
    id: "EMP-007",
    name: "Karthik Iyer",
    email: "karthik.iyer@peoplehub.io",
    role: "Backend Engineer",
    department: "Engineering",
    status: "active",
    joinDate: "2022-09-12",
    avatar: null,
    phone: "+91-32109-87654",
    location: "Bangalore, India",
  },
  {
    id: "EMP-008",
    name: "Deepa Nair",
    email: "deepa.nair@peoplehub.io",
    role: "Sales Executive",
    department: "Sales",
    status: "on-leave",
    joinDate: "2023-02-28",
    avatar: null,
    phone: "+91-21098-76543",
    location: "Kochi, India",
  },
  {
    id: "EMP-009",
    name: "Rahul Joshi",
    email: "rahul.joshi@peoplehub.io",
    role: "DevOps Engineer",
    department: "Engineering",
    status: "active",
    joinDate: "2021-08-14",
    avatar: null,
    phone: "+91-10987-65432",
    location: "Bangalore, India",
  },
  {
    id: "EMP-010",
    name: "Meera Gupta",
    email: "meera.gupta@peoplehub.io",
    role: "Operations Manager",
    department: "Operations",
    status: "active",
    joinDate: "2022-12-01",
    avatar: null,
    phone: "+91-09876-54321",
    location: "Gurgaon, India",
  },
  {
    id: "EMP-011",
    name: "Aditya Verma",
    email: "aditya.verma@peoplehub.io",
    role: "Data Engineer",
    department: "Engineering",
    status: "active",
    joinDate: "2023-05-22",
    avatar: null,
    phone: "+91-98712-34560",
    location: "Noida, India",
  },
  {
    id: "EMP-012",
    name: "Kavitha Sundaram",
    email: "kavitha.s@peoplehub.io",
    role: "Content Strategist",
    department: "Marketing",
    status: "active",
    joinDate: "2023-08-10",
    avatar: null,
    phone: "+91-87612-34509",
    location: "Chennai, India",
  },
];

const leaveRequests = [
  {
    id: "LR-001",
    employeeId: "EMP-003",
    employeeName: "Ravi Kumar",
    type: "Sick Leave",
    startDate: "2026-05-05",
    endDate: "2026-05-07",
    reason: "Recovering from flu",
    status: "approved",
    appliedOn: "2026-05-04",
  },
  {
    id: "LR-002",
    employeeId: "EMP-005",
    employeeName: "Vikram Singh",
    type: "Casual Leave",
    startDate: "2026-05-05",
    endDate: "2026-05-06",
    reason: "Family function",
    status: "approved",
    appliedOn: "2026-05-01",
  },
  {
    id: "LR-003",
    employeeId: "EMP-008",
    employeeName: "Deepa Nair",
    type: "Earned Leave",
    startDate: "2026-05-05",
    endDate: "2026-05-12",
    reason: "Vacation trip to Goa",
    status: "approved",
    appliedOn: "2026-04-20",
  },
  {
    id: "LR-004",
    employeeId: "EMP-001",
    employeeName: "Arjun Mehta",
    type: "Work From Home",
    startDate: "2026-05-08",
    endDate: "2026-05-08",
    reason: "Internet installation at new apartment",
    status: "pending",
    appliedOn: "2026-05-05",
  },
  {
    id: "LR-005",
    employeeId: "EMP-007",
    employeeName: "Karthik Iyer",
    type: "Sick Leave",
    startDate: "2026-05-10",
    endDate: "2026-05-11",
    reason: "Dental surgery scheduled",
    status: "pending",
    appliedOn: "2026-05-04",
  },
  {
    id: "LR-006",
    employeeId: "EMP-012",
    employeeName: "Kavitha Sundaram",
    type: "Casual Leave",
    startDate: "2026-05-15",
    endDate: "2026-05-16",
    reason: "Personal errands",
    status: "pending",
    appliedOn: "2026-05-05",
  },
];

const announcements = [
  {
    id: "ANN-001",
    title: "Q2 Town Hall — May 15th",
    message:
      "Join us for the quarterly town hall meeting. CEO will share company updates and roadmap.",
    date: "2026-05-02",
    priority: "high",
  },
  {
    id: "ANN-002",
    title: "New Health Insurance Policy",
    message:
      "We've upgraded our health insurance coverage. Check your email for the updated policy document.",
    date: "2026-05-01",
    priority: "medium",
  },
  {
    id: "ANN-003",
    title: "Office Closed — May 26th (Holiday)",
    message:
      "The office will remain closed on May 26th on account of a public holiday.",
    date: "2026-04-28",
    priority: "low",
  },
];
